Device config upload endpoint
AntuanW/AGH-Engineering-Thesis pull request #25
Opened 2024-11-04 15:52 UTC by zolszowka

2024-11-05 16:56 UTC, GrigoryM1A1 requested changes

2024-11-05 16:56 UTC, GrigoryM1A1 commented on backend/app/config_upload/config_upload_service.py
> +            device.disconnect()
Przydałby się jakikolwiek error handling.
Ja bym się też zastanowił czy tu nie lepiej będzie użyć `with statement` z pythona (czyli takie a'la try-with-resources w Javie), jeśli nie no to na pewno ten error handling, gdzie disconnect chyba powinno być robione w bloku `finally`.

2024-11-05 16:56 UTC, GrigoryM1A1 commented on backend/app/config_upload/models/netmiko_device.py
IMO trochę zwodnicza nazwa tego package'a, bo w pierwsze tempo myślałem, że chodzi o modele, które są wykorzystywane przy bazie danych. Np. coś w stylu util.

2024-11-05 16:56 UTC, GrigoryM1A1 commented on backend/app/config_upload/netmiko_config_builder.py
Rozumiem, że te zahardkodowane rzeczy to tymczasowo, bo nie ma jeszcze  tego modelu w bazie ogarniętego, tak? Jeśli tak to proszę komentuj też takie rzeczy.

Ale jeszcze pytanie do idei tego buildera... czy to jest tylko jakaś konwencja na nazwanie tej klasy czy to ma związek z tym wzorcem projektowym Builder? Bo jak to drugie to chyba coś nie do końca pykło w implementacji, a przynajmniej ja kojarzę, że to trochę inaczej powinno wyglądać. 
Np tak jak tutaj (tylko niekoniecznie musi być ten director):
https://sbcode.net/python/builder/#source-code

2024-11-05 16:56 UTC, GrigoryM1A1 commented on backend/app/routes/upload_config_router.py
> +    config_upload_service.upload_configs(devices)
No i tu znowu jakiś error handling. Nawet jakiś basicowy, bo będzie łatwiej później w debugowaniu.

2024-11-06 16:39 UTC, GrigoryM1A1 commented on backend/app/config_upload/util/netmiko_device.py
> +        self.disconnect()
O, a to fajne, nawet nie wiedziałem, że tak się da. Ale dla pewności wolę dopytać - to jest nadpisywane po to, żeby skorzystać z tego `with statement`, tak?

2024-11-06 16:39 UTC, GrigoryM1A1 commented on backend/app/config_upload/config_upload_service.py
> +                raise DeviceConnectionError(f"Failed to connect to {device.host}. Error:{e}")
Tutaj nie lepszym pomysłem byłoby zrobienie error handlingu tak jak np w linijkach 123-129 w `upload_config_router.py`? Mam na myśli skorzystanie z jednego bloku `try` i dwóch `except` na tym samym poziomie.

No i ten ogólny wyjątek `Exception` trochę mi nie siedzi. Jeśli wiemy jakie wyjątki mogą rzucić te metody (a podejrzewam, że w dokumentacji jest to opisane - popraw mnie jeśli jednak nie) to starajmy się łapać te konkretne wyjątki, a dopiero na sam koniec jeśli nie mamy pewności czy to wszystkie to zrobić takiego `excepta` z łapaniem ogólnego wyjątku.

2024-11-07 14:58 UTC, zolszowka commented on backend/app/config_upload/util/netmiko_device.py
> +        self.disconnect()
Dokładnie tak

2024-11-07 15:04 UTC, GrigoryM1A1 approved these changes
LGTM

2024-11-07 15:13 UTC, merged